#!/usr/bin/env bash
# Ensure the script is run as root

sudo apt-get update -y
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to redirect /redirect_me to another page with a 301 status
cat <<EOL >> /etc/nginx/sites-available/default

server {
    listen 80;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

# Restart Nginx to apply changes without using systemctl
service nginx restart
