#!/usr/bin/env bash
# Ensure the script is run as root

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Update package list and install nginx
apt-get update
apt-get install -y nginx

# Create an HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Create the custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to redirect /redirect_me to another page with a 301 status
# and to use the custom 404 error page
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80;

    # Root location
    location / {
        try_files \$uri \$uri/ =404;
    }

    # Redirection configuration
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOL

# Restart Nginx to apply changes without using systemctl
service nginx restart
