#!/usr/bin/env bash
# configures a new Ubuntu machine

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="add_header X-Served-By $HOST_NAME;"
FIND=$(grep "add_header X-Served-By" /etc/nginx/sites-available/default)
sed -i "/server_name _;/a \\t$HEADER" /etc/nginx/sites-available/default

# Create a first index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
FIND=$(grep "location /redirect_me" /etc/nginx/sites-available/default)
STRING="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}"
sed -i "/server_name _;/a \\t$STRING" /etc/nginx/sites-available/default

# Add to the nginx configuration file a custom 404 error page
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="error_page 404 /custom_404.html;"
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/server_name _;/a \\t$ERROR" /etc/nginx/sites-available/default

# Restart nginx to apply the changes
service nginx restart
