#!/usr/bin/env bash
# backup and compress my databases

# variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
mysql_root_password="$1"

# Perform MySQL dump
mysqldump --all-databases -u root --password="$mysql_root_password" > /tmp/backup.sql;

# Compress the SQL dump
tar -czvf "/tmp/$file_name" -C /tmp backup.sql;

# Clean up the uncompressed SQL dump
rm /tmp/backup.sql
