#!/usr/bin/env bash
# Define the signal handlers

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Get the PID of the script
pid=$$

# Write the PID to the file /var/run/myscript.pid
echo "$pid" > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
