#!/usr/bin/env bash
# Using a while loop to display time from 0:01 to 12:59

hour=0

while ((hour <= 12))
do
	echo "Hour: $hour"
	minute=1
	while ((minute <= 59))
	do
		printf "%d\n" $minute
		((minute++))
	done
	((hour++))
done
