#!/usr/bin/env bash
# Checking information about the school file using if and else

file="school"

if [[ -e "$file" ]]; then
	echo $file file exists
	if [[ ! -s "$file" ]]; then
		echo $file file is empty
	else
		echo $file file is not empty
	fi
	if [[ -f "$file" ]]; then
		echo $file is a regular file
	fi
else
	echo $file file does not exist
	exit 1
fi
