#!/usr/bin/env bash
# Checking information about the school file using if and else

file="school"

if [[ -e "$file" ]]; then
	echo "school file exists"
	if [[ -s "$file" ]]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [[ -f "$file" ]]; then
		echo "school is a regular file"
	else
		echo "school is not a regular file"
	fi
else
	echo "school file does not exist"
fi
