#!/usr/bin/env bash
# Install and configure UFW firewall on web-01

# Update package list and install UFW
sudo apt-get update
sudo apt-get install ufw -y

# Allow SSH, HTTP, and HTTPS ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Set default policies to deny incoming traffic and allow outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Enable the firewall
sudo ufw enable

# Check the status of UFW
sudo ufw status
